### ISSUE TITLE
Import Issue from `bpmn-client`

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [ralphhanna/bpmn-server#110]
Hi @ralphhanna

It seems to be an issue with the `import` from `bpmn-client`.
When `bpmn-client` tries to `import`, I receive an error in the webapp of  `bpmn-server`.

**Client Side:**

```shell
import  HNSample F:\bpmn-client-app\.workflows\HNSample.bpmn F:\bpmn-client-app\.workflows\HNSample.svg
upload failed: Request failed with status code 400
```

**Server Side (Webapp) Error:**

```shell
 importing: HNSample
request.body {}
***************BPMNServer UNCAUGHT ERROR*********** Error: ENOENT: no such file or directory, open 'F:\bpmn-webapp\routes/../tmp/HNSample.bpmn'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at Multipart.<anonymous> (F:\bpmn-webapp\routes\api.js:256:43)
    at Multipart.emit (node:events:513:28)
    at HeaderParser.cb (F:\bpmn-webapp\node_modules\busboy\lib\types\multipart.js:358:14)
    at HeaderParser.push (F:\bpmn-webapp\node_modules\busboy\lib\types\multipart.js:162:20)
    at SBMH.ssCb [as _cb] (F:\bpmn-webapp\node_modules\busboy\lib\types\multipart.js:394:37)
    at feed (F:\bpmn-webapp\node_modules\streamsearch\lib\sbmh.js:219:14)
    at SBMH.push (F:\bpmn-webapp\node_modules\streamsearch\lib\sbmh.js:104:16)
    at Multipart._write (F:\bpmn-webapp\node_modules\busboy\lib\types\multipart.js:567:19) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'F:\\bpmn-webapp\\routes/../tmp/HNSample.bpmn'
}
POST /api/definitions/import/HNSample - - ms - -
```

Kindly look into this. Thank you!

**Comment by ralphhanna** [comment]
Did you make sure that you have the latest version of both client and sever

Sent from my iPhone

On Jul 11, 2023, at 10:52 AM, Maheshkumar Sundaram ***@***.***> wrote:

﻿

Hi @ralphhanna<https://github.com/ralphhanna>

It seems to be an issue with the import from bpmn-client.
When bpmn-client tries to import, I receive an error in the webapp of bpmn-server.

Client Side:

import  HNSample F:\bpmn-client-app\.workflows\HNSample.bpmn F:\bpmn-client-app\.workflows\HNSample.svg
upload failed: Request failed with status code 400

Server Side (Webapp) Error:

 importing: HNSample
request.body {}
***************BPMNServer UNCAUGHT ERROR*********** Error: ENOENT: no such file or directory, open 'F:\bpmn-webapp\routes/../tmp/HNSample.bpmn'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at Multipart.<anonymous> (F:\bpmn-webapp\routes\api.js:256:43)
    at Multipart.emit (node:events:513:28)
    at HeaderParser.cb (F:\bpmn-webapp\node_modules\busboy\lib\types\multipart.js:358:14)
    at HeaderParser.push (F:\bpmn-webapp\node_modules\busboy\lib\types\multipart.js:162:20)
    at SBMH.ssCb [as _cb] (F:\bpmn-webapp\node_modules\busboy\lib\types\multipart.js:394:37)
    at feed (F:\bpmn-webapp\node_modules\streamsearch\lib\sbmh.js:219:14)
    at SBMH.push (F:\bpmn-webapp\node_modules\streamsearch\lib\sbmh.js:104:16)
    at Multipart._write (F:\bpmn-webapp\node_modules\busboy\lib\types\multipart.js:567:19) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'F:\\bpmn-webapp\\routes/../tmp/HNSample.bpmn'
}
POST /api/definitions/import/HNSample - - ms - -

Instead of looking for tmp/ under root path, it's looking for the files inside routes/../tmp.

Kindly look into this. Thank you!

**Comment by ralphhanna** [comment]
Also, make sure that you have `tmp` folder that is writable under the web in your case `'F:\bpmn-webapp\tmp`

**Comment by MaheshkumarSundaram** [comment]
Hi @ralphhanna 

I am using the updated versions of both client and server. 

Also in the error message from the webapp:

![image](https://github.com/ralphhanna/bpmn-server/assets/55505611/1718df1c-f215-4dfa-80ab-33bc90400219)
![image](https://github.com/ralphhanna/bpmn-server/assets/55505611/920c1128-7830-4f3a-9f4b-df12b9574cfe)


It's not looking for the file inside `tmp` of the root path but instead its looking inside `routes`.

**Comment by ralphhanna** [comment]
It’s looking at tmp inside the parent of routes

Sent from my iPhone

On Jul 12, 2023, at 4:56 AM, Maheshkumar Sundaram ***@***.***> wrote:

﻿

Hi @ralphhanna<https://github.com/ralphhanna>

I am using the updated versions of both client and server.

Also in the error message from the webapp:

[image]<https://user-images.githubusercontent.com/55505611/252914060-1718df1c-f215-4dfa-80ab-33bc90400219.png>
[image]<https://user-images.githubusercontent.com/55505611/252913736-920c1128-7830-4f3a-9f4b-df12b9574cfe.png>

It's not looking for the file inside tmp of the root path but instead its looking inside routes.

**Comment by MaheshkumarSundaram** [comment]
Hi @ralphhanna

Thank you. On a related note, I think it would be less of a hassle if there is another option to directly provide the contents of BPMN and SVG instead of using files. Something like, `server.definitions.importContent(name, bpmnContent, svgContent)`, an alternative to files and paths & the webapp with server too use those contents directly instead of using files.
What do you think?

**Comment by MaheshkumarSundaram** [comment]
@ralphhanna,

I did a fresh installation of `bpmn-server`.

>> Also, make sure that you have tmp folder that is writable under the web in your case 'F:\bpmn-webapp\tmp

The folder permissions are fine. and there is nothing wrong with that. I tested it with a simple script

```
const fs = require('fs');

const textContent = `This a test file
Dummy content

by Mahesh`;


fs.writeFile('F:\\Programming\\bpmn-webapp\\routes/../tmp/TESTFile.bpmn', textContent, err => {
  if (err) {
    console.error(err);
  }
  // file written successfully
});

```
![image](https://github.com/ralphhanna/bpmn-server/assets/55505611/856b1848-a7cd-4f3b-9d64-8b5434536a1b)

And I can write to that folder,

But when I use `bpmn-client` to import a file (the bpmn path used below has the xml file correctly.),

```
await bpmnServer.definitions.import(
            params.workflowName,
            path.join(workflowsPath, `${params.workflowName}.bpmn`),
            //path.join(workflowsPath, `${params.workflowName}.svg`),
        );
```

**Client Error:**
![image](https://github.com/ralphhanna/bpmn-server/assets/55505611/b9f126f3-448f-4e51-a745-3b8bb07b149e)

**Serverside Error:**

```shell
 importing: HNSample
request.body {}
***************BPMNServer UNCAUGHT ERROR*********** Error: ENOENT: no such file or directory, open 'F:\Programming\bpmn-webapp\routes/../tmp/HNSample.bpmn'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at Multipart.<anonymous> (F:\Programming\bpmn-webapp\routes\api.js:256:43)
    at Multipart.emit (node:events:513:28)
    at HeaderParser.cb (F:\Programming\bpmn-webapp\node_modules\busboy\lib\types\multipart.js:358:14)
    at HeaderParser.push (F:\Programming\bpmn-webapp\node_modules\busboy\lib\types\multipart.js:162:20)
    at SBMH.ssCb [as _cb] (F:\Programming\bpmn-webapp\node_modules\busboy\lib\types\multipart.js:394:37)
    at feed (F:\Programming\bpmn-webapp\node_modules\streamsearch\lib\sbmh.js:200:10)
    at SBMH.push (F:\Programming\bpmn-webapp\node_modules\streamsearch\lib\sbmh.js:104:16)
    at Multipart._write (F:\Programming\bpmn-webapp\node_modules\busboy\lib\types\multipart.js:567:19) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'F:\\Programming\\bpmn-webapp\\routes/../tmp/HNSample.bpmn'
}
```
The thing is that file gets created inside `tmp` folder but there is no content.

![image](https://github.com/ralphhanna/bpmn-server/assets/55505611/08ecaa15-b2ee-44f5-af51-a0d1542144d2)

I don't think there is any issue with folder permissions as tested above and `import` has been working fine in the previous versions of server and client.

This is puzzling. I can't understand why it's not working.

Any help would be appreciated. Thanks!

**Comment by ralphhanna** [comment]
I am not able to see the problem, but have remove writing to tmp folder by reading into memory in new Release 1.3.27
Please update the server and see

**Comment by MaheshkumarSundaram** [comment]
Hi @ralphhanna 

Thank you so much. It works now as it doesn't use files anymore.

I am not sure what the problem with the files was. I'll try it investigating on my end, too, and I will update if I find anything.

Thanks.
