### ISSUE TITLE
Issue in creating a new model using WebApp

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [ralphhanna/bpmn-server#35]
**Description:**
Error when trying to create a new model using the WebApp,

**Steps to Reproduce:**
1) Open the [webapp](http://localhost:3000/)
2) Click "New Model"
3) Give a service name
4) Click "Submit"
5) See the error in console

**Expected behaviour:**
Allow me to create a new model and save it

**Console Error:**
```
node:fs:599
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'F:\Programming\Test-BPMN-Server/processes/testServiceOptions.bpmn'
    at Object.openSync (node:fs:599:3)
    at Object.readFileSync (node:fs:467:35)
    at ModelsDatastore.getFile (F:\Programming\Test-BPMN-Server\node_modules\bpmn-server\dist\src\datastore\ModelsDatastore.js:246:23)
    at ModelsDatastore.<anonymous> (F:\Programming\Test-BPMN-Server\node_modules\bpmn-server\dist\src\datastore\ModelsDatastore.js:259:25)
    at Generator.next (<anonymous>)
    at F:\Programming\Test-BPMN-Server\node_modules\bpmn-server\dist\src\datastore\ModelsDatastore.js:9:71
    at new Promise (<anonymous>)
    at __awaiter (F:\Programming\Test-BPMN-Server\node_modules\bpmn-server\dist\src\datastore\ModelsDatastore.js:5:12)
    at ModelsDatastore.getSource (F:\Programming\Test-BPMN-Server\node_modules\bpmn-server\dist\src\datastore\ModelsDatastore.js:258:16)
    at Modeller.<anonymous> (F:\Programming\Test-BPMN-Server\views\Modeller.js:22:37) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'F:\\Programming\\Test-BPMN-Server/processes/testServiceOptions.bpmn'
}
```

**P.S:** Tested in the [demo site](https://bpmn.omniworkflow.com/) as well

**Comment by ralphhanna** [comment]
oops, a fix is coming shortly

**Comment by ralphhanna** [comment]
Ok, new release is now available, please either re-install or just update
In either case, please repeat copy files after install
Thanks

**Comment by MaheshkumarSundaram** [comment]
Thank you for your quick response and fix.
