### ISSUE TITLE
Error triggering Signal

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [ralphhanna/bpmn-server#52]
**_Using 1.3.5_**

I tried running the already available example `test-throw` which in turn triggers `test-catch`.

When the end signal event is about to be triggered by `test-catch`, there is an error:

```shell
GET /instanceDetails?id=a2e71126-7fc8-40e7-bd5a-9853befc3dc2 200 93.849 ms - -
service  checkOutService completed-output undefined undefined
bpmnServerTest\node_modules\bpmn-server\src\elements\Node.js:81
            if (Object.keys(item.context.output).length == 0)
                       ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at EndEvent.<anonymous> (bpmnServerTest\node_modules\bpmn-server\src\elements\Node.js:81:24)
    at Generator.next (<anonymous>)
    at bpmnServerTest\node_modules\bpmn-server\src\elements\Node.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (bpmnServerTest\node_modules\bpmn-server\src\elements\Node.js:4:12)
    at EndEvent.getOutput (bpmnServerTest\node_modules\bpmn-server\src\elements\Node.js:80:16)
    at SignalEventBehaviour.<anonymous> (bpmnServerTest\node_modules\bpmn-server\src\elements\behaviours\MessageSignal.js:68:48)
    at Generator.next (<anonymous>)
    at bpmnServerTest\node_modules\bpmn-server\src\elements\behaviours\MessageSignal.js:8:71

Node.js v18.7.0
```

Kindly look into this. 

Thanks!

**Comment by ralphhanna** [comment]
Fixed in release 1.3.6
added more testing.
Thanks
