### ISSUE TITLE
Error in `bpmn-client` when querying instances or items

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [ralphhanna/bpmn-server#80]
Hi @ralphhanna,

_Using `bpmn-client` version `1.3.16`._

When I try to use `cli.ts` to do some querying, all give the error:

```
BPMNClient 1.2
Commands:
        q       to quit
        s       start process
        lo      list outstanding items
        li      list items
        l       list instances for a process
        di      display Instance information
        i       Invoke Task
        sgl     Signal Task
        msg     Message Task
        d       delete instnaces
        ?       repeat this list
Enter Command, q to quit
>lo
Listing Outstanding Items

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (F:\Programming\dicomHubScripts\node_modules\bpmn-client\src\BPMNClient.js:41:52)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

>di
Displaying Instance Details
Please provide your Instance ID: cd5f065a-a3b9-4189-85ad-4769d1527502

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (F:\Programming\dicomHubScripts\node_modules\bpmn-client\src\BPMNClient.js:41:52)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

>di
Displaying Instance Details
Please provide your Instance ID: "cd5f065a-a3b9-4189-85ad-4769d1527502"

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (F:\Programming\dicomHubScripts\node_modules\bpmn-client\src\BPMNClient.js:41:52)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

Could you kindly look into this? Thank you!

**Comment by ralphhanna** [comment]
Very sorry for the late response, please try it out with https (port 443)
I am getting this error msg also when using http not https, I have no idea why.
Would welcome your help in debugging it, it seems that http.request 'data' event not firing.

**Comment by MaheshkumarSundaram** [comment]
Hi @ralphhanna,

I changed the `port` from `3000` to `443` in the `.env` file for `bpmn-client`.

But I recieve the error:
![image](https://user-images.githubusercontent.com/55505611/229733619-188d2c81-18ba-438f-86e2-986c7de52d7d.png)

Do I have to do anything else on the `bpmn-server` to get it right?

Thanks

**Comment by ralphhanna** [comment]
No problem, I have a new release in the pipeline to fix this problem

**Comment by ralphhanna** [comment]
New Release 1.3.17 for bpmnClient is now available to fix this problem
